import {
  type JSX,
  type KeyboardEvent,
  type MouseEvent,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from "react";
import { useTranslation } from "react-i18next";
import { useToast } from "../../components/Toast";
import { localizeConnectionError } from "../../lib/errors";
import type { Connection } from "../../lib/tauri";
import { deleteConnection, duplicateConnection } from "../../lib/tauri";
import { useEditor } from "../editor/store";
import { useHealth } from "../health";
import { useSchema } from "../schema/store";
import { EnvironmentBadge } from "./EnvironmentBadge";
import { useConnections } from "./store";

/**
 * Sidebar list of saved connections (spec §5.3).
 *
 * - Pure `.map()` over the Zustand store; no virtualization (target ≤50 rows).
 * - Keyboard nav: ↑/↓ moves selection, Enter opens edit, Delete opens confirm.
 * - Right-click opens an inline context menu with Edit / Duplicate / Delete.
 * - Delete shows a confirm-by-typing dialog (matches the Radix Dialog pattern
 * ; behaviourally identical so the integration agent can
 * swap the inline dialog for the Radix wrapper without test churn).
 */
export function ConnectionList(): JSX.Element {
  const { t } = useTranslation();
  const toast = useToast();
  const connections = useConnections((s) => s.connections);
  const selectedId = useConnections((s) => s.selectedId);
  const select = useConnections((s) => s.select);
  const openEditForm = useConnections((s) => s.openEditForm);
  const upsertLocal = useConnections((s) => s.upsertLocal);
  const removeLocal = useConnections((s) => s.removeLocal);

  const [menuTargetId, setMenuTargetId] = useState<string | null>(null);
  const [confirmTargetId, setConfirmTargetId] = useState<string | null>(null);
  const [confirmTyped, setConfirmTyped] = useState("");
  const [query, setQuery] = useState("");

  const filteredConnections = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (q.length === 0) return connections;
    return connections.filter((c) => {
      const haystack = `${c.name} ${c.host}:${c.port} ${c.database}`.toLowerCase();
      return haystack.includes(q);
    });
  }, [connections, query]);

  // Close any open inline menu when clicking outside the list area.
  useEffect(() => {
    if (menuTargetId === null) return;
    const onDocClick = () => setMenuTargetId(null);
    document.addEventListener("click", onDocClick);
    return () => document.removeEventListener("click", onDocClick);
  }, [menuTargetId]);

  // Close the delete-confirm dialog on Escape regardless of focus location.
  useEffect(() => {
    if (confirmTargetId === null) return;
    const onKey = (e: globalThis.KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        setConfirmTargetId(null);
        setConfirmTyped("");
      }
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [confirmTargetId]);

  const onRowClick = useCallback(    (id: string) => {
      select(id);
    },
    [select],
);

  const onContextMenu = useCallback(    (event: MouseEvent<HTMLDivElement>, id: string) => {
      event.preventDefault();
      event.stopPropagation();
      select(id);
      setMenuTargetId(id);
    },
    [select],
);

  const onEdit = useCallback(    (id: string) => {
      setMenuTargetId(null);
      openEditForm(id);
    },
    [openEditForm],
);

  const onDuplicate = useCallback(    async (conn: Connection) => {
      setMenuTargetId(null);
      try {
        // Server-side duplicate copies the password from the OS keychain
        // so the new entry is immediately usable (audit M4). The unique
        // name " copy" suffix is generated by Rust to avoid clashing with
        // an existing duplicate.
        const created = await duplicateConnection(conn.id);
        upsertLocal(created);
        toast.success(t("toast.connection.duplicated"));
      } catch (err) {
        toast.error(localizeConnectionError(err, t));
      }
    },
    [upsertLocal, toast, t],
);

  const openDelete = useCallback((id: string) => {
    setMenuTargetId(null);
    setConfirmTargetId(id);
    setConfirmTyped("");
  }, []);

  const confirmDelete = useCallback(async () => {
    if (confirmTargetId === null) return;
    const id = confirmTargetId;
    try {
      // If the schema browser is bound to this connection, drop its state
      // BEFORE we remove the row from the connections store — otherwise the
      // banner / tabs end up pointing at a now-deleted id.
      const schemaState = useSchema.getState();
      const schemaTouchesId =
        schemaState.connection.status !== "idle" && schemaState.connection.connId === id;
      if (schemaTouchesId) {
        await schemaState.disconnect();
      }
      await deleteConnection(id);
      // — Health Screen cleanup. Drop in-memory Health state,
      // close the Health tab if open, and remove the per-conn LS entry.
      try {
        useHealth.getState().clearConn(id);
      } catch {
        // throwing-stub — ignore until implements.
      }
      try {
        await useEditor.getState().closeTab(`health-${id}`);
      } catch {
        // Tab may not exist; closeTab returns false in that case.
      }
      try {
        window.localStorage.removeItem(`ide99:health.refreshInterval.${id}`);
      } catch {
        // best-effort
      }
      removeLocal(id);
      toast.success(t("toast.connection.deleted"));
      setConfirmTargetId(null);
      setConfirmTyped("");
    } catch (err) {
      toast.error(localizeConnectionError(err, t));
    }
  }, [confirmTargetId, removeLocal, toast, t]);

  const onListKeyDown = useCallback(    (event: KeyboardEvent<HTMLDivElement>) => {
      const visible = filteredConnections;
      if (visible.length === 0) return;
      const currentIdx = visible.findIndex((c) => c.id === selectedId);
      if (event.key === "ArrowDown") {
        event.preventDefault();
        const next = visible[Math.min(Math.max(currentIdx, -1) + 1, visible.length - 1)];
        if (next) select(next.id);
      } else if (event.key === "ArrowUp") {
        event.preventDefault();
        const next = visible[Math.max(currentIdx - 1, 0)];
        if (next) select(next.id);
      } else if (event.key === "Enter") {
        if (selectedId) {
          event.preventDefault();
          openEditForm(selectedId);
        }
      } else if (event.key === "Delete" || event.key === "Backspace") {
        if (selectedId) {
          event.preventDefault();
          openDelete(selectedId);
        }
      }
    },
    [filteredConnections, selectedId, select, openEditForm, openDelete],
);

  const confirmRow = confirmTargetId
    ? connections.find((c) => c.id === confirmTargetId)
    : undefined;
  const menuRow = menuTargetId ? connections.find((c) => c.id === menuTargetId) : undefined;

  const showSearch = connections.length > 0;
  const noMatches = showSearch && filteredConnections.length === 0 && query.trim().length > 0;

  return (    <>
      {showSearch ? (        <div style={{ padding: "4px 0 8px" }}>
          <input
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={t("connection.list.search_placeholder")}
            aria-label={t("connection.list.search_aria_label")}
            data-testid="connection-list-search"
            className="q-input"
            style={{ width: "100%", padding: "6px 8px", fontSize: 12 }}
          />
        </div>
) : null}
      <div
        // biome-ignore lint/a11y/useSemanticElements: native <select> would not allow our compound row structure (name + host:port subtitle)
        role="listbox"
        aria-label={t("connection.list.aria_label")}
        aria-activedescendant={selectedId ? `conn-row-${selectedId}` : undefined}
        tabIndex={0}
        onKeyDown={onListKeyDown}
        data-testid="connection-list"
        style={{ display: "flex", flexDirection: "column", gap: 4, paddingTop: 4 }}
      >
        {noMatches ? (          <div
            data-testid="connection-list-empty"
            style={{ padding: "8px 6px", color: "var(--ink-3)", fontSize: 12 }}
          >
            {t("connection.list.search_no_results")}
          </div>
) : null}
        {filteredConnections.map((conn) => {
          const isSelected = conn.id === selectedId;
          return (            <div
              key={conn.id}
              id={`conn-row-${conn.id}`}
              // biome-ignore lint/a11y/useSemanticElements: <option> only valid inside <select>; this is a custom listbox row
              role="option"
              tabIndex={-1}
              aria-selected={isSelected}
              onClick={() => onRowClick(conn.id)}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  onRowClick(conn.id);
                }
              }}
              onContextMenu={(e) => onContextMenu(e, conn.id)}
              className={`q-conn-row ${isSelected ? "selected" : ""}`}
            >
              <span className="name" title={conn.name}>
                <EnvironmentBadge environment={conn.environment} />
                <span className="name-text">{conn.name}</span>
              </span>
              <span className="meta" title={`${conn.host}:${conn.port}`}>
                {conn.host}:{conn.port}
              </span>
            </div>
);
        })}
      </div>

      {menuRow ? (        <div
          role="menu"
          className="q-popover"
          style={{ left: 14, marginTop: 4, width: 200 }}
          onClick={(e) => e.stopPropagation()}
          onKeyDown={() => {}}
        >
          <button
            type="button"
            role="menuitem"
            onClick={() => onEdit(menuRow.id)}
            className="q-popover-item"
          >
            {t("connection.list.context.edit")}
          </button>
          <button
            type="button"
            role="menuitem"
            onClick={() => void onDuplicate(menuRow)}
            className="q-popover-item"
          >
            {t("connection.list.context.duplicate")}
          </button>
          <hr className="q-popover-sep" />
          <button
            type="button"
            role="menuitem"
            onClick={() => openDelete(menuRow.id)}
            className="q-popover-item danger"
          >
            {t("connection.list.context.delete")}
          </button>
        </div>
) : null}

      {confirmRow ? (        // biome-ignore lint/a11y/useSemanticElements: <dialog> element lacks the styling/positioning hooks we need; aria role is sufficient
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="delete-confirm-title"
          style={{ position: "fixed", inset: 0, zIndex: 90 }}
          onKeyDown={(e) => {
            if (e.key === "Escape") {
              e.preventDefault();
              e.stopPropagation();
              setConfirmTargetId(null);
              setConfirmTyped("");
            }
          }}
        >
          <div className="q-backdrop" />
          <div className="q-modal sm" style={{ padding: 24 }}>
            <h3 id="delete-confirm-title" className="q-modal-title" style={{ userSelect: "text" }}>
              {t("connection.delete.confirm.title")}
            </h3>
            <p
              style={{
                marginTop: 8,
                fontSize: 12.5,
                color: "var(--ink-3)",
                userSelect: "text",
              }}
            >
              {t("connection.delete.confirm.body")}
            </p>
            <div className="q-field" style={{ marginTop: 14 }}>
              <label htmlFor="connection-list-delete-name-readonly">
                {t("connection.delete.confirm.name_label")}
              </label>
              <input
                id="connection-list-delete-name-readonly"
                type="text"
                readOnly
                value={confirmRow.name}
                onFocus={(e) => e.currentTarget.select()}
                className="q-input mono"
                style={{ background: "var(--bg-sunken)" }}
              />
            </div>
            <div className="q-field" style={{ marginTop: 10 }}>
              <label htmlFor="connection-list-delete-confirm-input">
                {t("connection.delete.confirm.type_prompt")}
              </label>
              <input
                id="connection-list-delete-confirm-input"
                type="text"
                value={confirmTyped}
                onChange={(e) => setConfirmTyped(e.target.value)}
                // biome-ignore lint/a11y/noAutofocus: focus the type-prompt input on dialog open — the modal is the only thing on screen, so the autofocus does not surprise screen-reader users.
                autoFocus
                className="q-input mono"
              />
            </div>
            <div
              style={{
                marginTop: 18,
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
              }}
            >
              <button
                type="button"
                onClick={() => {
                  setConfirmTargetId(null);
                  setConfirmTyped("");
                }}
                className="btn btn-ghost"
              >
                {t("connection.form.action.cancel")}
              </button>
              <button
                type="button"
                disabled={confirmTyped !== confirmRow.name}
                onClick={() => void confirmDelete()}
                className="btn btn-danger"
              >
                {t("connection.list.context.delete")}
              </button>
            </div>
          </div>
        </div>
) : null}
    </>
);
}
