import type { FunctionTemplate } from "./types";

const make = (name: string, signature: string): FunctionTemplate => ({
  name,
  signature,
  docI18nKey: `editor.functions.${name}.doc`,
});

export const BUILTIN_FUNCTIONS: readonly FunctionTemplate[] = Object.freeze([
  // aggregate
  make("count", "count(*) | count(expr) → bigint"),
  make("sum", "sum(expr) → numeric"),
  make("avg", "avg(expr) → numeric"),
  make("min", "min(expr) → same as expr"),
  make("max", "max(expr) → same as expr"),
  make("array_agg", "array_agg(expr) → anyarray"),
  make("string_agg", "string_agg(expr, delim) → text"),
  make("jsonb_agg", "jsonb_agg(expr) → jsonb"),
  make("jsonb_object_agg", "jsonb_object_agg(key, value) → jsonb"),
  make("bool_and", "bool_and(expr) → boolean"),
  make("bool_or", "bool_or(expr) → boolean"),
  make("bit_or", "bit_or(expr) → integer"),
  // window
  make("row_number", "row_number() OVER (…) → bigint"),
  make("rank", "rank() OVER (…) → bigint"),
  make("dense_rank", "dense_rank() OVER (…) → bigint"),
  make("percent_rank", "percent_rank() OVER (…) → double precision"),
  make("cume_dist", "cume_dist() OVER (…) → double precision"),
  make("ntile", "ntile(n) OVER (…) → integer"),
  make("lag", "lag(expr [, offset [, default]]) OVER (…) → same as expr"),
  make("lead", "lead(expr [, offset [, default]]) OVER (…) → same as expr"),
  make("first_value", "first_value(expr) OVER (…) → same as expr"),
  make("last_value", "last_value(expr) OVER (…) → same as expr"),
  make("nth_value", "nth_value(expr, n) OVER (…) → same as expr"),
  // string
  make("length", "length(text) → integer"),
  make("substring", "substring(text FROM start [FOR len]) → text"),
  make("trim", "trim([leading|trailing|both] [chars FROM] text) → text"),
  make("ltrim", "ltrim(text [, chars]) → text"),
  make("rtrim", "rtrim(text [, chars]) → text"),
  make("lower", "lower(text) → text"),
  make("upper", "upper(text) → text"),
  make("replace", "replace(text, from, to) → text"),
  make("split_part", "split_part(text, delim, n) → text"),
  make("regexp_replace", "regexp_replace(text, pattern, replacement [, flags]) → text"),
  make("regexp_matches", "regexp_matches(text, pattern [, flags]) → text[]"),
  make("format", "format(fmt, args…) → text"),
  // date/time
  make("now", "now() → timestamp with time zone"),
  make("current_timestamp", "current_timestamp → timestamp with time zone"),
  make("current_date", "current_date → date"),
  make("age", "age(timestamp [, timestamp]) → interval"),
  make("date_trunc", "date_trunc(field, source) → timestamp"),
  make("extract", "extract(field FROM source) → numeric"),
  make("to_char", "to_char(value, fmt) → text"),
  make("to_date", "to_date(text, fmt) → date"),
  make("to_timestamp", "to_timestamp(text, fmt) → timestamp with time zone"),
  make("make_date", "make_date(year, month, day) → date"),
  make("make_timestamp", "make_timestamp(year, month, day, hour, min, sec) → timestamp"),
  make("justify_interval", "justify_interval(interval) → interval"),
  // numeric
  make("abs", "abs(numeric) → numeric"),
  make("ceil", "ceil(numeric) → numeric"),
  make("floor", "floor(numeric) → numeric"),
  make("round", "round(numeric [, places]) → numeric"),
  make("mod", "mod(numeric, numeric) → numeric"),
  make("power", "power(base, exp) → numeric"),
  // jsonb
  make("jsonb_build_object", "jsonb_build_object(key, value, …) → jsonb"),
  make("jsonb_build_array", "jsonb_build_array(values…) → jsonb"),
  make("jsonb_set", "jsonb_set(jsonb, path[], replacement [, create_missing]) → jsonb"),
  make("jsonb_strip_nulls", "jsonb_strip_nulls(jsonb) → jsonb"),
  make("jsonb_object_keys", "jsonb_object_keys(jsonb) → setof text"),
  make("jsonb_typeof", "jsonb_typeof(jsonb) → text"),
  make("to_jsonb", "to_jsonb(any) → jsonb"),
  make("jsonb_array_elements", "jsonb_array_elements(jsonb) → setof jsonb"),
  make("jsonb_path_query", "jsonb_path_query(jsonb, jsonpath) → setof jsonb"),
  make("jsonb_pretty", "jsonb_pretty(jsonb) → text"),
  // array
  make("array_length", "array_length(anyarray, dim) → integer"),
  make("array_position", "array_position(anyarray, anyelement) → integer"),
  make("array_remove", "array_remove(anyarray, anyelement) → anyarray"),
  make("array_replace", "array_replace(anyarray, from, to) → anyarray"),
  make("unnest", "unnest(anyarray) → setof anyelement"),
  make("array_to_string", "array_to_string(anyarray, delim [, null_repr]) → text"),
  // conditional
  make("coalesce", "coalesce(args…) → same as args"),
  make("nullif", "nullif(a, b) → same as a"),
  make("greatest", "greatest(args…) → same as args"),
  make("least", "least(args…) → same as args"),
  // util
  make("cast", "cast(expr AS type) → type"),
  make("generate_series", "generate_series(start, stop [, step]) → setof"),
  make("pg_typeof", "pg_typeof(any) → regtype"),
  make("pg_column_size", "pg_column_size(any) → integer"),
]);
