#!/usr/bin/env bash
# scripts/bench-baseline.sh — capture a fresh perf baseline.
#
# Runs the four CI-gated benches (parser_bench, autocomplete_latency,
# explain_render, result_grid_format), then walks `target/criterion/`
# to harvest each bench's median and emits a `baselines.json` candidate
# to stdout. Pipe to `src-tauri/benches/baselines.json` after a sanity
# check.
#
# Usage:
#   bash scripts/bench-baseline.sh > /tmp/new-baseline.json
#   diff src-tauri/benches/baselines.json /tmp/new-baseline.json
#   cp /tmp/new-baseline.json src-tauri/benches/baselines.json
#
# When to refresh:
#   - Hardware change (new dev machine, CI runner)
#   - Intentional perf change merged on main (then re-baseline immediately)
#   - schema_version bump in baselines.json
#
# This script does NOT update target_max_ns (those are product targets,
# not measured); copy them through manually if you regenerate.
#
# Skipped benches (require a running Postgres / a built Tauri binary):
#   - cold_start (Tauri spawn + READY event)
#   - schema_introspection (testcontainers Postgres)
#   - history_search (testcontainers Postgres)
# Run those manually on a dev machine before a release.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/src-tauri"

# `--quick` cuts Criterion's sample budget roughly in half. The headline
# medians remain stable to within ~2% on a quiet machine, which is well
# inside the 10% regression tolerance. For a full-fat baseline drop the
# flag (~5–10× wall time).
QUICK="${BENCH_QUICK:---quick}"

BENCHES=(parser_bench autocomplete_latency explain_render result_grid_format)

>&2 echo "==> Capturing baseline ($(uname -sm))"
for b in "${BENCHES[@]}"; do
  >&2 echo "    cargo bench --bench $b $QUICK"
  cargo bench --bench "$b" -- $QUICK >&2
done

# Walk target/criterion and emit a JSON skeleton. Each Criterion bench
# writes `<bench_id>/new/estimates.json` with the median in nanoseconds.
# We map `<file>::<bench_id>` → its median.

>&2 echo "==> Harvesting medians from target/criterion"
python3 - "$ROOT/src-tauri/target/criterion" "${BENCHES[@]}" <<'PY'
import json, os, sys
crit_root = sys.argv[1]
benches = sys.argv[2:]

# Mapping from criterion subdir → (file_name, sub_id). Criterion writes
# bench_function("foo") → criterion/foo/. bench_with_input under a
# group → criterion/<group>/<value>/. We can't disambiguate which bench
# file produced which subdir from disk alone, so we use a known list:
# each bench file tags every BenchmarkId with a function name unique to
# that file (verified by code review of the bench sources).
known = {
    'parser_bench': ['parse_ddl_100lines', 'parse_select_typical'],
    'autocomplete_latency': [
        'autocomplete_parse_corpus/all_queries',
        'autocomplete_parse_corpus/query/0',
        'autocomplete_parse_corpus/query/1',
        'autocomplete_parse_corpus/query/2',
        'autocomplete_parse_corpus/query/3',
        'autocomplete_parse_corpus/query/4',
        'autocomplete_parse_corpus/query/5',
        'autocomplete_parse_corpus/query/6',
        'autocomplete_parse_corpus/query/7',
        'autocomplete_parse_corpus/query/8',
        'autocomplete_parse_corpus/query/9',
        'autocomplete_scope_extraction_corpus',
        'autocomplete_parse_64_join_query',
    ],
    'explain_render': [
        'explain_parse_500_nodes_fixture',
        'explain_walk_500_nodes_fixture',
        'explain_insights_500_nodes_fixture',
        'explain_parse_50_nodes',
        'explain_parse_25_nodes',
    ],
    'result_grid_format': [
        'result_grid_serialize/query_result_to_json/1000',
        'result_grid_serialize/query_result_to_json/10000',
        'result_grid_serialize/query_result_to_json/100000',
    ],
}

def median_ns(bench_dir):
    p = os.path.join(bench_dir, 'new', 'estimates.json')
    if not os.path.isfile(p):
        return None
    with open(p) as fh:
        data = json.load(fh)
    pe = data.get('median', {}).get('point_estimate')
    return int(pe) if pe is not None else None

out = {}
missing = []
for fname, ids in known.items():
    for bid in ids:
        bench_dir = os.path.join(crit_root, bid)
        m = median_ns(bench_dir)
        key = f'{fname}::{bid}'
        if m is None:
            missing.append(key)
            continue
        out[key] = m

if missing:
    sys.stderr.write(f'WARNING: medians not found for: {missing}\n')

import datetime, platform
captured_on = f'{platform.system().lower()}-{platform.machine()} / {platform.processor() or "unknown CPU"}'
result = {
    '_comment': 'Generated by scripts/bench-baseline.sh — review medians before committing.',
    'schema_version': 1,
    'captured_at': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    'captured_on': captured_on,
    'captured_by': os.environ.get('USER', 'unknown'),
    'tolerance_pct': 10,
    'benches': {k: {'median_ns': v, 'target_max_ns': None, 'notes': ''} for k, v in sorted(out.items())},
}
print(json.dumps(result, indent=2))
PY
